[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
dns-server = 114.114.114.114, 223.5.5.5, 119.29.29.29, 8.8.8.8
ipv6 = true

[Rule]
DST-PORT,65010,PROXY
DST-PORT,10012,PROXY

DOMAIN-KEYWORD,anticheatexpert,REJECT
DOMAIN-KEYWORD,gamesafe,REJECT
DOMAIN,android.crashsight.qq.com,REJECT
DOMAIN,h.trace.qq.com,REJECT
DOMAIN,cloud.tgpa.qq.com,REJECT
DOMAIN,cloudctrl.gcloud.qq.com,REJECT
DOMAIN,api.xunyou.mobi,REJECT
DOMAIN,api.unipay.qq.com,REJECT

DOMAIN,log.tinput.qq.com,REJECT
DOMAIN,monitor.uu.qq.com,REJECT
DOMAIN,mtrace.qq.com,REJECT
DOMAIN,vmp.qq.com,REJECT
DOMAIN,oth.str.mdt.qq.com,REJECT
DOMAIN,test.gamesafe.qq.com,REJECT
DOMAIN,exp.qq.com,REJECT
DOMAIN,broker.tga.qq.com,REJECT

DOMAIN-SUFFIX,tgpa.qq.com,PROXY
DOMAIN-SUFFIX,game.qq.com,PROXY
DOMAIN-SUFFIX,idip.qq.com,PROXY
DOMAIN-KEYWORD,pvp.qq.com,PROXY
DOMAIN-KEYWORD,tmgp.qq.com,PROXY

DOMAIN-KEYWORD,intlgame,DIRECT
DOMAIN-KEYWORD,uam,DIRECT
DOMAIN-KEYWORD,heipingjingying,DIRECT
DOMAIN-KEYWORD,anqutuwei,DIRECT
DOMAIN,df.gcloudcdn.qq.com,DIRECT
DOMAIN,hc.tdm.qq.com,DIRECT
DOMAIN,bsy.uam.tcdnos.com,DIRECT
DOMAIN,guid.tpns.tencent.com,DIRECT
DOMAIN,sg.intlgame.com,DIRECT
DOMAIN,snowflake.qq.com,DIRECT

DOMAIN-SUFFIX,weixin.qq.com,DIRECT
DOMAIN-SUFFIX,wechat.com,DIRECT
DOMAIN-KEYWORD,apple.com,DIRECT
DOMAIN-KEYWORD,icloud.com,DIRECT
DOMAIN-SUFFIX,snssdk.com,DIRECT
DOMAIN-SUFFIX,amap.com,DIRECT

IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
FINAL,DIRECT
