[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
dns-server = 119.29.29.29, 223.5.5.5, 114.114.114.114, 8.8.8.8

[Rule]
DOMAIN-SUFFIX,ip-api.com,PROXY
DOMAIN-SUFFIX,ipify.org,PROXY

DST-PORT,65010,PROXY
DST-PORT,10012,PROXY
DST-PORT,10013,PROXY
DST-PORT,17500,PROXY

DOMAIN-KEYWORD,gtimg,DIRECT
DOMAIN-KEYWORD,itop,DIRECT
DOMAIN-KEYWORD,msdk,DIRECT
DOMAIN-KEYWORD,gcloud,DIRECT
DOMAIN-KEYWORD,syzs,DIRECT
DOMAIN-SUFFIX,igamecj.com,DIRECT
DOMAIN-SUFFIX,tgpa.qq.com,DIRECT
DOMAIN-SUFFIX,game.qq.com,DIRECT
DOMAIN-SUFFIX,idip.qq.com,DIRECT
DOMAIN-KEYWORD,pvp.qq.com,DIRECT
DOMAIN-KEYWORD,tmgp.qq.com,DIRECT

DOMAIN-KEYWORD,anticheatexpert,PROXY
DOMAIN-KEYWORD,crashsight,PROXY
DOMAIN-KEYWORD,gamesafe,PROXY
DOMAIN,log.tinput.qq.com,PROXY
DOMAIN,monitor.uu.qq.com,PROXY
DOMAIN,mtrace.qq.com,PROXY
DOMAIN,vmp.qq.com,PROXY
DOMAIN,oth.str.mdt.qq.com,PROXY
DOMAIN,test.gamesafe.qq.com,PROXY
DOMAIN,exp.qq.com,PROXY
DOMAIN,broker.tga.qq.com,PROXY

IP-CIDR,180.109.156.92/32,PROXY,no-resolve
IP-CIDR,153.3.50.229/32,PROXY,no-resolve
IP-CIDR,36.155.240.19/32,PROXY,no-resolve
IP-CIDR,119.45.69.203/32,PROXY,no-resolve
IP-CIDR,182.254.116.0/24,PROXY,no-resolve
IP-CIDR,182.254.11.0/24,PROXY,no-resolve

DOMAIN-KEYWORD,qq.com,DIRECT
DOMAIN-SUFFIX,weixin.qq.com,DIRECT
DOMAIN-SUFFIX,wechat.com,DIRECT
DOMAIN-KEYWORD,apple.com,DIRECT
DOMAIN-KEYWORD,icloud.com,DIRECT

IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
FINAL,DIRECT

