[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
dns-server = 114.114.114.114, 223.5.5.5
ipv6 = true

[Rule]
# === 1. 核心防封拦截 (丢弃反作弊组件与崩溃上报) ===
DOMAIN-KEYWORD,anticheatexpert,REJECT
DOMAIN-KEYWORD,gamesafe,REJECT
DOMAIN,android.crashsight.qq.com,REJECT
DOMAIN,h.trace.qq.com,REJECT
DOMAIN,cloud.tgpa.qq.com,REJECT
DOMAIN,cloudctrl.gcloud.qq.com,REJECT
DOMAIN,api.xunyou.mobi,REJECT
DOMAIN,api.unipay.qq.com,REJECT

# === 2. 游戏正常业务直连放行 (防误杀断网) ===
DOMAIN-KEYWORD,intlgame,DIRECT
DOMAIN-KEYWORD,uam,DIRECT
DOMAIN-KEYWORD,heipingjingying,DIRECT
DOMAIN-KEYWORD,anqutuwei,DIRECT
DOMAIN,df.gcloudcdn.qq.com,DIRECT
DOMAIN,hc.tdm.qq.com,DIRECT
DOMAIN,bsy.uam.tcdnos.com,DIRECT
DOMAIN,guid.tpns.tencent.com,DIRECT
DOMAIN,sg.intlgame.com,DIRECT
DOMAIN,snowflake.qq.com,DIRECT

# === 3. 游戏战斗服 (需客户在小火箭里自己选好代理节点) ===
DST-PORT,65010,PROXY
DST-PORT,10012,PROXY

# === 4. 兜底规则 (没写在上面的普通上网流量，统统直连) ===
FINAL,DIRECT
